version: "3"
services:
  service-config:
    build: service-config
    ports:
     - "8888:8888"
    restart: always 
    volumes:
     - ./service-config # modified here to take into account the new app path
  service-register:
    build: service-register
    ports:
     - "8761:8761"
    restart: always 
    volumes:
     - ./service-register # modified here to take into account the new app path