FROM node:latest
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/upload

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm cache verify
RUN npm install
RUN npm install @angular/cli
# RUN npm install -D sonarqube-scanner
# add app
COPY . /usr/src/app

# start app
CMD ng serve --port 4201 --configuration=dev --host 0.0.0.0 --disableHostCheck