FROM node as build
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app
COPY ./src/environments/environment.taxi.ts /app/src/environments/environment.prod.ts

ARG configuration=production
RUN npm run build -- --outputPath=./dist/out --configuration $configuration
# Stage 2, use the compiled app, ready for production with Nginx
FROM nginx
COPY --from=build /app/dist/out/ /usr/share/nginx/html
COPY /nginx-custom.conf /etc/nginx/conf.d/default.conf
